ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

RUN apt-get update && apt-get upgrade -y
# Install Archive manager
RUN apt-get install -y file-roller unzip inotify-tools

# Install Sudo
RUN apt-get install -y sudo && echo 'kasm-user ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers && rm -rf /var/lib/apt/list/*

# Add Custom Background
ADD /zandbak_background.png  /usr/share/backgrounds/bg_default.png

# Install Remnux Utils
#COPY ./src/ubuntu/install/remnux $INST_SCRIPTS/remnux/
#RUN bash $INST_SCRIPTS/remnux/install_remnux.sh && rm -rf $INST_SCRIPTS/remnux/

# Install Brave
COPY ./src/ubuntu/install/brave $INST_SCRIPTS/brave/
RUN bash $INST_SCRIPTS/brave/install_brave.sh  && rm -rf $INST_SCRIPTS/brave/

# COPY ./src/ubuntu/install/brave/custom_startup.sh $STARTUPDIR/custom_startup.sh
# RUN chmod +x $STARTUPDIR/custom_startup.sh

# Install Google Chrome
COPY ./src/ubuntu/install/chrome $INST_SCRIPTS/chrome/
RUN bash $INST_SCRIPTS/chrome/install_chrome.sh  && rm -rf $INST_SCRIPTS/chrome/

# Security modifications
# COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
# RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/
# COPY ./src/common/chrome-managed-policies/urlblocklist.json /etc/opt/chrome/policies/managed/urlblocklist.json

# Setup the custom startup script that will be invoked when the container starts
#ENV LAUNCH_URL  http://kasmweb.com

COPY ./src/ubuntu/install/chrome/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh

# Install auto-unzip watcher for the Uploads folder
COPY ./auto_unzip.sh $STARTUPDIR/auto_unzip.sh
RUN chmod +x $STARTUPDIR/auto_unzip.sh && \
    sed -i 's|kasm_startup() {|kasm_startup() {\n    /dockerstartup/auto_unzip.sh \&|' $STARTUPDIR/custom_startup.sh


# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

# Install Libre Office
COPY ./src/ubuntu/install/libre_office $INST_SCRIPTS/libre_office/
RUN bash $INST_SCRIPTS/libre_office/install_libre_office.sh  && rm -rf $INST_SCRIPTS/libre_office/

### Install WINE
COPY ./src/ubuntu/install/wine $INST_SCRIPTS/wine/
RUN bash $INST_SCRIPTS/wine/install_wine.sh  && rm -rf $INST_SCRIPTS/wine/

# Install Thunderbird
COPY ./src/ubuntu/install/thunderbird $INST_SCRIPTS/thunderbird/
RUN bash $INST_SCRIPTS/thunderbird/install_thunderbird.sh  && rm -rf $INST_SCRIPTS/thunderbird/

# Install Thunderbird add-ons via enterprise policy
RUN mkdir -p /usr/lib/thunderbird/distribution && \
    curl -sSL "https://addons.thunderbird.net/thunderbird/downloads/latest/safe-links-cleaner/addon-988025-latest.xpi" \
        -o /usr/lib/thunderbird/safe-links-cleaner.xpi && \
    curl -sSL "https://addons.thunderbird.net/thunderbird/downloads/latest/web_translate/addon-987924-latest.xpi" \
        -o /usr/lib/thunderbird/web-translate.xpi && \
    echo '{"policies":{"Extensions":{"Install":["file:///usr/lib/thunderbird/safe-links-cleaner.xpi","file:///usr/lib/thunderbird/web-translate.xpi"]}}}' \
        > /usr/lib/thunderbird/distribution/policies.json

# Install VSCode
COPY ./src/ubuntu/install/vs_code $INST_SCRIPTS/vs_code/
RUN bash $INST_SCRIPTS/vs_code/install_vs_code.sh  && rm -rf $INST_SCRIPTS/vs_code/

# Install Insomnia
COPY ./src/ubuntu/install/insomnia $INST_SCRIPTS/insomnia/
RUN bash $INST_SCRIPTS/insomnia/install_insomnia.sh  && rm -rf $INST_SCRIPTS/insomnia/

# Ensure the Desktop directory and shortcut have correct permissions
RUN chown -R 1000:0 $HOME/Desktop

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
